---
title: "Intermediate R: Getting help, advanced data wrangling, and functions"
subtitle: "Session 7"
date: "2023-09-26"
date-format: long
format: uaz-revealjs
chalkboard: true
footer: "[Reproduciblity & Data Science in R](../../index.html)"
logo: "../../logo.png"
---

# Learning objectives

-   Write a data wrangling script using tidy verbs
-   Convert a tailor-made script to a function

# Part I: Getting help

-   See the [Getting Help](../11-getting-help/slides.html) section!

# Part II: Hands-on data wrangling

## Picking up from last week

-   Commit last week's work to GitHub and push
-   Merge your work to main!
-   Create a new branch for today's work and pull

## Data wrangling objectives:

-   Use `mutate` to convert units of columns
-   Use `summarize` to calculate group-wise summary statistics
-   Use `pivot_wider` to create cross-tabs
-   Use "tidy selection" helpers to reduce repetition in this workflow!

# Part III: Functions

## What are functions in R?

-   We use pre-written functions constantly.
-   Automated "recipes" for executing code
-   Inputs ("arguments") and outputs

## Why write our own functions?

-   Avoid repetition (+ mistakes)
-   Enhance portability + reproducibility

## Writing a function objectives

-   Convert our data wrangling script into a function
-   Break this function into smaller, human-readable functions
-   Make this function flexible to apply to other data

## A note on conditionals

-   `if` and `ifelse` statements balance readability and flexibility in functions

## Conditionals in R

-   `==` for "is equal to"
-   `!=` for "not equal to:
-   `<`, `>` for less than/greater than
-   `<=`, `>=` for less than or equal to/greater than or equal to
-   `is.na()` for is it NA?
-   `%in%` for, is this value in a vector of possibilities
-   ...and more!

## Finishing up

-   Commit your changes and push
-   Open a pull request.

## Show and tell (Late October)

-   An opportunity to apply workshop skills to your own work.
-   You could apply different parts to different projects, or more integratively to one single project.
-   Optional, but encouraged!

## Some inspirations

-   Turn the project folder for one of your current research project into a git/GitHub repo and/or R project
-   Modify an R script to use functions, conditionals, or best-practices for code formatting
-   Improve directory organization for project or your entire computer!
