project:
  type: website
  render:
    - "!instructor-notes.qmd"

website:
  title: "repro-data-sci"
  repo-url: https://github.com/cct-datascience/repro-data-sci
  repo-actions: [edit, issue]
  site-url: https://cct-datascience.github.io/repro-data-sci/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - about.qmd
      - text: Instructor Notes
        menu:
          - href: "lessons/1-project-management/notes.qmd"
            text: "1. Project Management"
          - href: "lessons/2-shell/notes.qmd"
            text: "2. Shell Commands"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

