project:
  type: website

website:
  title: "repro-data-sci"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - about.qmd
      - text: Instructor Notes
        menu:
          - "lessons/1-shell/notes.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

