project:
  type: website
  resources: 
    - "robots.txt"
  render: 
    - "*.qmd"
    
execute: 
  freeze: auto

website:
  title: "Reproducibility & Data Science in R"
  repo-url: https://github.com/cct-datascience/repro-data-sci
  repo-actions: [edit, issue]
  site-url: https://cct-datascience.github.io/repro-data-sci/
  navbar:
    tools:
      - icon: github
        text: Source #shows on hover
        href: https://github.com/cct-datascience/repro-data-sci
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Instructor Notes
        menu:
          - href: "lessons/1-project-management/notes.qmd"
            text: "1. Project Management"
          - href: "lessons/2-markdown-quarto/notes.qmd"
            text: "2. Documentation & Literate Programming"
          - href: "lessons/3-shell/notes.qmd"
            text: "3. Shell Commands"
          - href: "lessons/4-git/notes.qmd"
            text: "4. Version Control With Git"
          - href: "lessons/5-github-basics/notes.qmd"
            text: "5. Developing Code on GitHub"
          - href: "lessons/6-github-collab/notes.qmd"
            text: "6. Collaborating with GitHub"
          - href: "lessons/7-data-manipulation/notes.qmd"
            text: "7. Data Manipulation"
          - href: "lessons/8-intermediate-r-1/notes.qmd"
            text: "8. Intermediate R I"
          - href: "lessons/9-intermediate-r-2/notes.qmd"
            text: "9. Intermediate R II"
          - href: "lessons/10-get-credit/notes.qmd"
            text: "10. Getting Credit For Your Hard Work"

format:
  html:
    theme: 
      - sandstone #feel free to change to a different one https://bootswatch.com/
      - custom.scss
    css: https://use.typekit.net/emv3zbo.css #proxima-nova font
    toc: true
    
editor: 
  markdown:
    wrap: sentence
    canonical: true

citation: 
  type: webpage
  container-title: "Reproducibility & Data Science in R"
  author: 
    - Eric Scott
    - Renata Diaz
    - Jessica Guo
    - Kristina Riemer
  issued: 2024
  doi: 10.5281/zenodo.8411612