project:
  type: website
    
execute: 
  freeze: auto

website:
  title: "Reproducibility & Data Science in R"
  repo-url: https://github.com/cct-datascience/repro-data-sci
  repo-actions: [edit, issue]
  site-url: https://cct-datascience.github.io/repro-data-sci/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Instructor Notes
        menu:
          - href: "lessons/1-project-management/notes.qmd"
            text: "1. Project Management"
          - href: "lessons/2-shell/notes.qmd"
            text: "2. Shell Commands"
          - href: "lessons/3-git/notes.qmd"
            text: "3. Version Control With Git"
          - href: "lessons/4-github-basics/notes.qmd"
            text: "4. Developing Code on GitHub"
          - href: "lessons/5-github-collab/notes.qmd"
            text: "5. Collaborating with GitHub"
          - href: "lessons/6-data-manipulation/notes.qmd"
            text: "6. Data Manipulation"
          - href: "lessons/7-intermediate-r-1/notes.qmd"
            text: "7. Intermediate R I"
          - href: "lessons/8-intermediate-r-2/notes.qmd"
            text: "8. Intermediate R II"
          - href: "lessons/9-markdown-quarto/notes.qmd"
            text: "9. Documentation & Literate Programming"
          - href: "lessons/10-get-credit/notes.qmd"
            text: "10. Getting Credit For Your Hard Work"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
editor: 
  markdown:
    wrap: sentence
    canonical: true

