---
title: "Reproducibility Colloquium"
---

The [final session](index.qmd#schedule) of this workshop series is our ✨**Reproducibility Colloquium**✨, where you all get a chance to share what you've learned with each other and anyone you'd like to invite to attend.
You are invited to give a short (about 5min) talk with slides (about 5).
To make this as low stakes as possible, here is an outline you may follow when putting together your presentation.

::: callout-important
For each slide, you don't need to address **all** of the bullet points—focus on what is relevant for the specific aspects of your project you focused on!
:::

::: callout-note
Feel free to adapt this outline—add or remove slides as fits your project.
:::

-   Slide 1: Super short description of your project for a ***general audience.***[^1]
-   Slide 2: Describe the data and code components of your project.
    -   What data types/sources do you work with?
        -   Hand-collected field data? A data compilation? Instrument data?
        -   Data type (e.g., numeric, survey responses, DNA sequences, geospatial)?
        -   File types and sizes?
    -   What computational tools are you using, and what are you using them for?
        -   e.g. Excel for data entry; R for data cleaning and analysis; Illustrator for polishing figures
-   Slide 3: Which aspects of the project did you focus on improving? What was the state of the project before the "makeover"?
    -   e.g. "I focused on transitioning to using git for version control; previously, I was saving my scripts with a new name each time I worked on them."
    -   Screen shots of the "before" are encouraged as visuals
-   Slide 4: What changes did you make as part of the "makeover"?
    -   Why did you focus on these?
    -   How did you implement the changes?
    -   Screen shots of the "after" are encouraged as visuals
-   Slide 5: Reflections
    -   What are you most proud of about this?
    -   Did you run into any challenges?
    -   What do you see as the next steps?

[^1]: This is a good opportunity to practice an elevator pitch!
    Try to keep it to just a couple sentences—just enough background to give some context to your data and code.
    The goal of the presentation is to focus on your project organization and reproducibility, *not* the details of your research topic.
