---
title: Reproducibility and Data Science in R
subtitle: "Fall 2024"
format: html
citation:
  title: Syllabus
---

Welcome to the syllabus for the CCT Data Science fall workshop series: **Reproducibility and Data Science in R.** If you didn't register for the course this year, sign up for our [mailing list](https://datascience.cct.arizona.edu/contact) to be notified when enrollment opens for next year's iteration and to be notified of our other monthly workshops.

## Schedule

We'll meet on Tuesdays and Thursdays from 11am to 1pm via Zoom (link pinned in Slack channel)


<!-- Edit by editing schedule.csv. To add links, use markdown [text](url) separated by commas. This code turns that into a bulleted list.-->

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(gt)
read_csv("schedule.csv") |>
  select(-Notes) |> 
  #turn comma separated list into markdown bullet points
  mutate(
    Links = str_replace(Links, ", ", "\n- ") |> 
      str_replace("^", "- ")
  ) |>
  gt() |>
  fmt_markdown(Links) |> 
  fmt_date(Date, date_style = "MEd") |> 
  sub_missing() |> 
  cols_align("left") |> 
  cols_width(
    Lesson ~ pct(10),
    Date ~ pct(15),
    Theme ~ pct(20),
    Topic ~ pct(35),
    Links ~ pct(20)
  )
```

## Code of Conduct

> Our group's mission is to enable scientists.
> This means treating people with respect and responding in a polite and helpful way.
>
> Our group is committed to ensuring a harassment-free experience for everyone, regardless of level of experience, gender, gender identity and expression, sexual orientation, disability, personal appearance, body size, race, ethnicity, age, or religion.
>
> Examples of unacceptable behavior by members, collaborators, and contributors include: the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

Read our full [code of conduct](https://cct-datascience.github.io/group-procedures/code-of-conduct.html) and please report any violations or concerns to the course instructors or to Kristina Riemer ([kristinariemer\@arizona.edu](mailto:kristinariemer@arizona.edu)).

## Helpful Reads

This workshop series doesn't have anything like "required reading", but we think these books and websites are good companions.

Data analysis in R:

-   [R for Data Science (2e)](https://r4ds.hadley.nz/)
-   [Building reproducible analytical pipelines with R](https://raps-with-r.dev/) <!--# I don't love this, but seems like there should be more than one resource here -->

Best practices for reproducibility:

-   [Good enough practices in scientific computing](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510)
-   [Data organization in spreadsheets](https://doi.org/10.1080/00031305.2017.1375989)
-   [A beginner's guide to conducting reproducible research](https://doi.org/10.1002/bes2.1801)
-   [The Turing Way: Guide for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research)
-   [6 Steps Toward Reproducible Research](https://zenodo.org/records/12744715)

Version control:

-   [Excuse me, do you have a moment to talk about version control?](https://doi.org/10.7287/peerj.preprints.3159v2)
-   [Happy Git and GitHub for the useR](https://happygitwithr.com/)
