---
title: "Getting Credit For Your Hard Work"
format: 
  html: default
  typst: default
bibliography: references.bib
---

## Objective

Learn the wrap-up steps to publish/archive a research compendium with a DOI.
Understand reproducible computational environment.
Learn `renv` and discuss Docker (concept).

## Lesson Outline

-   Why share code?

    -   Facilitate discussion
    -   Show figure from @maitner
    -   Higher citations
    -   To "pay it forward" to other researchers
    -   To demonstrate your skills
    -   To facilitate error correction

-   Getting credit for code

    -   Code is not cited often, but partly because it's not made easy to cite

-   CITATION.cff

    -   Show CITATION.cff files for this repo and maybe one for a research compendium
    -   Show "cite this" button on GitHub
    -   Show CITATION.cff creation tool [CFFINIT](https://citation-file-format.github.io/cff-initializer-javascript/#/)
    -   Maybe mention `cffr::cff_validate()`

-   Archiving

    -   Most participants probably won't be ready to follow along with their own repos, but we will be there to help when they are ready
    -   Demo archiving a repo with Zenodo using this repo
    -   Add DOI badge to readme
    -   Update CITATION.cff with DOI

-   `renv`

    -   Discuss why
    -   Ask students to activate `renv` for a project and inspect files it creates (have co-instructor share screen)
    -   Explain how `renv` works, especially `renv::status()` , and `renv::snapshot()`
    -   Clone co-instructor's repo with `renv` files
        -   Show that no packages are available initially (project is isolated)
        -   run `renv::restore()`

-   Docker (if time)

    -   Conceptual overview of what it is

    -   Discuss how tools like `renv` and Docker both help and hinder reproducibility

## Homework

-   Prep for showcase session
